package de.fuseki.coursemangement.enums;

public enum CourseChangeEnum implements MenuMarker{
    COURSE_CHANGE_ENUM,
    COURSE_CHANGE_LIST_STUDENTS,
    COURSE_CHANGE_TITLE,
    COURSE_CHANGE_DESCRIPTION,
    COURSE_CHANGE_LECTURERID,
    COURSE_CHANGE_ADDRESS,
    COURSE_CHANGE_DATEBEGIN,
    COURSE_CHANGE_DATEEND,
    COURSE_CHANGE_ENUM_EXIT
}
